version: '3.8'

services:
  postgres:
    image: postgres
    restart: always

    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
      - POSTGRES_DB=shopping
    ports:
      - "5432:5432"